- type: dungeonConfig
  id: CP14DemiplanePlatingMaskBorder
  layers:
  - !type:NoiseDistanceDunGen
    size: 140, 140
    distanceConfig: !type:DunGenEuclideanSquaredDistance
      blendWeight: 1
    layers:
    - tile: Plating
      threshold: 0.50
      noise:
        frequency: 0.010
        noiseType: OpenSimplex2
        fractalType: FBm
        octaves: 5
        lacunarity: 2
        gain: 0.5