- type: entity
  abstract: true
  parent: Clothing
  id: CP14ClothingPantsBase
  categories: [ ForkFiltered ]
  components:
  - type: Clothing
    equipDelay: 1
    unequipDelay: 1
    slots:
    - pants
  - type: Sprite
    state: icon