- type: entity
  abstract: true
  parent: Clothing
  id: CP14ClothingPantsBase
  categories: [ ForkFiltered ]
  description: Pants to cover my thighs from the cold.
  components:
  - type: Clothing
    equipDelay: 1
    unequipDelay: 1
    slots:
    - pants
  - type: Sprite
    state: icon

- type: entity
  parent: CP14ClothingPantsBase
  id: CP14ClothingPantsDress
  abstract: true
  description: A roomy, feminine skirt
  components:
  - type: Clothing
    equipDelay: 1.5
    unequipDelay: 1
    slots:
    - pants