- type: entity
  id: CPBaseWeaponChemical
  abstract: true
  components:
  - type: SolutionContainerManager
    solutions:
      melee:
        maxVol: 4
  - type: MeleeChemicalInjector
    solution: melee
  - type: RefillableSolution
    solution: melee
  - type: InjectableSolution
    solution: melee
  - type: SolutionInjectOnEmbed
    transferAmount: 2
    solution: melee
  - type: SolutionTransfer
    maxTransferAmount: 2

- type: entity
  id: CPBaseWeaponThrowable
  abstract: true
  components: 
  - type: ThrowingAngle
    angle: 225
  - type: EmbeddableProjectile
    offset: 0.15,0.15
    removalTime: 1
  - type: DamageOtherOnHit
    damage:
      types:
        Piercing: 10
  - type: DamageOnLand
    damage:
      types:
        Piercing: 10
  - type: Fixtures
    fixtures:
      fix1:
        shape: !type:PolygonShape
          vertices:
            - -0.40,-0.30
            - -0.30,-0.40
            - 0.40,0.30
            - 0.30,0.40
        density: 10
        mask:
        - ItemMask
        restitution: 0.3
        friction: 0.2

- type: entity
  id: CPBaseWeaponLight
  abstract: true
  components:
  - type: MeleeWeapon
    resetOnHandSelected: false
    
# Simple melee weapons

# Battle Staff
# Mace
# Stick
# Spear
# Light Hammer
# Throwing spear
# Hand axe
# Sickle

# Military melee weapons

# Halberd
# Battle pick
# Warhammer
# Battle axe
# Glaive

# Long spear
# Long sword
# Whip
# Short sword
# Hammer
# Morgenstern
# Pika
# Rapier
# Axe
# Scimitar
# Trident
# Chain