- type: entity
  id: CP14BaseWeaponChemical
  abstract: true
  components:
  - type: SolutionContainerManager
    solutions:
      melee:
        maxVol: 4
  - type: MeleeChemicalInjector
    solution: melee
  - type: RefillableSolution
    solution: melee
  - type: InjectableSolution
    solution: melee
  - type: SolutionInjectOnEmbed
    transferAmount: 2
    solution: melee
  - type: SolutionTransfer
    maxTransferAmount: 2

- type: entity
  id: CP14BaseWeaponThrowable
  abstract: true
  components: 
  - type: DamageOtherOnHit
    damage:
      types:
        Piercing: 10
  - type: DamageOnLand
    damage:
      types:
        Piercing: 10
  - type: Fixtures
    fixtures:
      fix1:
        shape: !type:PolygonShape
          vertices:
            - -0.40,-0.30
            - -0.30,-0.40
            - 0.40,0.30
            - 0.30,0.40
        density: 10
        mask:
        - ItemMask
        restitution: 0.3
        friction: 0.2

- type: entity
  id: CP14BaseWeaponLight
  abstract: true
  components:
  - type: MeleeWeapon
    resetOnHandSelected: false

- type: entity
  id: CP14BaseWeaponShort
  abstract: true
  components: 
  - type: MeleeWeapon
    range: 1.0 # 1.5 standart
    cPAnimationOffset: -0.75

- type: entity
  id: CP14BaseWeaponSharp
  abstract: true
  components:
  - type: Sharp
  - type: CP14Sharpened
  - type: CP14SharpeningStone
  - type: UseDelay

- type: entity
  id: CP14BaseWeaponDestructible
  abstract: true
  components:
  - type: ExaminableDamage
    messages: CP14WeaponMessages
  - type: Damageable
    damageContainer: Inorganic
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 50
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          collection: MetalBreak
      - !type:DoActsBehavior
        acts: ["Destruction"]