- type: entity
  parent: 
  - CP14ClothingCloakBase
  - ClothingSlotBase
  id: CP14ClothingCloakCommandantJacket
  name: commandant's jacket
  description: the colors white and gold tell you that you're looking at a higher power.
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Cloak/Roles/Bank/commandant_jacket.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Cloak/Roles/Bank/commandant_jacket.rsi