- type: entity
  parent: CP14ClothingCloakBase
  id: CP14ClothingCloakFurcapeBlack
  name: furcape
  description: Brutal woolen wool cape.
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Cloak/Roles/General/furcape2.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Cloak/Roles/General/furcape2.rsi

- type: entity
  parent: CP14ClothingCloakBase
  id: CP14ClothingCloakFurcapeBlue
  name: furcape
  description: Brutal woolen wool cape.
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Cloak/Roles/General/furcape.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Cloak/Roles/General/furcape.rsi

- type: entity
  parent: CP14ClothingCloakBase
  id: CP14ClothingCloakRitualAttireLeather
  name: ritual attire with leather
  description: The traditional attire of Southern mages who have undergone the ritual.
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Cloak/Roles/General/cheetah_skin.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Cloak/Roles/General/cheetah_skin.rsi

- type: entity
  parent: CP14ClothingCloakBase
  id: CP14ClothingCloakWhite
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Cloak/Roles/General/white.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Cloak/Roles/General/white.rsi