- type: antag
  id: CP14Sociopath
  name: cp14-roles-antag-sociopath-name
  antagonist: true
  setPreference: true
  objective: cp14-roles-antag-sociopath-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 7200 # 2h
  #guides: TODO

- type: startingGear
  id: CP14SociopathGear
  storage:
    back:
    - CP14BaseLockpick
    - CP14BaseLockpick
    - CP14BaseLockpick