using Content.Client.Resources;
using Content.Shared._CP14.Fishing.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._CP14.Fishing.UI;

[GenerateTypedNameReferences]
public sealed partial class CP14FishingWindow : BaseWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IResourceCache _resourceCache = default!;
    public CP14FishingWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public void InitVisuals(CP14FishingRodComponent component)
    {
        FishingWindow.Visible = false;

        // Getting data
        if (!_prototypeManager.Resolve(component.FishingMinigame, out var minigameStyle))
            return;

        var background = minigameStyle.Background;
        var floatUI = minigameStyle.Float;
        var progressbar = minigameStyle.Progressbar;
        var fishIcon = minigameStyle.FishIcon;

        FishingWindow.SetSize = background.Size;

        Progressbar.MaxSize = progressbar.Size;
        Progressbar.Margin = new Thickness(progressbar.Offset.X, 0, 0, progressbar.Offset.Y);

        Float.SetSize = floatUI.Size;
        Float.Margin = new Thickness(floatUI.Offset.X, 0, 0, floatUI.Offset.Y);

        FishIcon.SetSize = fishIcon.Size;
        FishIcon.Margin = new Thickness(fishIcon.Offset.X, 0, 0, fishIcon.Offset.Y);

        var backgroundTexture = _resourceCache.GetTexture(background.Texture);
        FishingBackground.PanelOverride = new StyleBoxTexture
        {
            Texture = backgroundTexture,
        };

        var progressbarTexture = _resourceCache.GetTexture(progressbar.Texture);
        Progressbar.PanelOverride = new StyleBoxTexture
        {
            Texture = progressbarTexture,
        };

        var floatTexture = _resourceCache.GetTexture(floatUI.Texture);
        Float.PanelOverride = new StyleBoxTexture
        {
            Texture = floatTexture,
        };

        var fishTexture = _resourceCache.GetTexture(fishIcon.Texture);
        FishIcon.PanelOverride = new StyleBoxTexture
        {
            Texture = fishTexture,
        };

        FishingWindow.Visible = true;
    }
}

