- type: entity
  parent: BaseMobSpecies
  id: CP14BaseMobSpecies
  save: false
  abstract: true
  components:
    - type: Sprite
      layers:
        - map: [ "enum.HumanoidVisualLayers.Chest" ]
        - map: [ "enum.HumanoidVisualLayers.Head" ]
        - map: [ "enum.HumanoidVisualLayers.Snout" ]
        - map: [ "enum.HumanoidVisualLayers.Eyes" ]
        - map: [ "enum.HumanoidVisualLayers.RArm" ]
        - map: [ "enum.HumanoidVisualLayers.LArm" ]
        - map: [ "enum.HumanoidVisualLayers.RLeg" ]
        - map: [ "enum.HumanoidVisualLayers.LLeg" ]
        - shader: StencilClear
          sprite: Mobs/Species/Human/parts.rsi #PJB on stencil clear being on the left leg: "...this is 'fine'" -https://github.com/space-wizards/space-station-14/pull/12217#issuecomment-1291677115
          # its fine, but its still very stupid that it has to be done like this instead of allowing sprites to just directly insert a stencil clear.
          # sprite refactor when
          state: l_leg
        - shader: StencilMask
          map: [ "enum.HumanoidVisualLayers.StencilMask" ]
          sprite: Mobs/Customization/masking_helpers.rsi
          state: unisex_full
          visible: false
        - map: [ "jumpsuit" ]
        - map: [ "pants" ]
        - map: [ "shirt" ]
        - map: [ "enum.HumanoidVisualLayers.LFoot" ]
        - map: [ "enum.HumanoidVisualLayers.RFoot" ]
        - map: [ "enum.HumanoidVisualLayers.LHand" ]
        - map: [ "enum.HumanoidVisualLayers.RHand" ]
        - map: [ "gloves" ]
        - map: [ "shoes" ]
        - map: [ "ears" ]
        - map: [ "outerClothing" ]
        - map: [ "eyes" ]
        - map: [ "belt" ]
        - map: [ "id" ]
        - map: [ "neck" ]
        - map: [ "cloak" ]
        - map: [ "back" ]
        - map: [ "enum.HumanoidVisualLayers.FacialHair" ]
        - map: [ "enum.HumanoidVisualLayers.Hair" ]
        - map: [ "enum.HumanoidVisualLayers.HeadSide" ]
        - map: [ "enum.HumanoidVisualLayers.HeadTop" ]
        - map: [ "enum.HumanoidVisualLayers.Tail" ]
        - map: [ "mask" ]
        - map: [ "head" ]
        - map: [ "pocket1" ]
        - map: [ "pocket2" ]
        - map: ["enum.HumanoidVisualLayers.Handcuffs"]
          color: "#ffffff"
          sprite: Objects/Misc/handcuffs.rsi
          state: body-overlay-2
          visible: false
        - map: [ "clownedon" ] # Dynamically generated
          sprite: "Effects/creampie.rsi"
          state: "creampie_human"
          visible: false
    - type: HumanoidAppearance
      species: CP14Human
    - type: Body
      prototype: CP14Human
      requiredLegs: 2

- type: entity
  parent: BaseMobSpeciesOrganic
  id: CP14BaseMobSpeciesOrganic
  save: false
  abstract: true
  #components:
  #  - type: FireVisuals
  #    alternateState: Standing #TO DO - custom visual

- type: entity
  save: false
  parent: BaseSpeciesDummy
  id: CP14BaseSpeciesDummy
  abstract: true
  components:
  - type: Inventory
    templateId: CP14Human
  - type: Icon
    sprite: _CP14/Mobs/Species/Human/parts.rsi
    state: full
  - type: Sprite
    drawdepth: Mobs
    noRot: true
    layers:
    - map: [ "enum.HumanoidVisualLayers.Chest" ]
    - map: [ "enum.HumanoidVisualLayers.Head" ]
    - map: [ "enum.HumanoidVisualLayers.Snout" ]
    - map: [ "enum.HumanoidVisualLayers.Eyes" ]
    - map: [ "enum.HumanoidVisualLayers.RArm" ]
    - map: [ "enum.HumanoidVisualLayers.LArm" ]
    - map: [ "enum.HumanoidVisualLayers.RLeg" ]
    - map: [ "enum.HumanoidVisualLayers.LLeg" ]
    - shader: StencilClear
      sprite: Mobs/Species/Human/parts.rsi
      state: l_leg
    - shader: StencilMask
      map: ["enum.HumanoidVisualLayers.StencilMask"]
      sprite: Mobs/Customization/masking_helpers.rsi
      state: unisex_full
      visible: false
    - map: ["jumpsuit"]
    - map: ["enum.HumanoidVisualLayers.LFoot"]
    - map: ["enum.HumanoidVisualLayers.RFoot"]
    - map: ["enum.HumanoidVisualLayers.LHand"]
    - map: ["enum.HumanoidVisualLayers.RHand"]
    - map: ["enum.HumanoidVisualLayers.Handcuffs"]
      color: "#ffffff"
      sprite: Objects/Misc/handcuffs.rsi
      state: body-overlay-2
      visible: false
    - map: [ "gloves" ]
    - map: [ "ring1" ]
    - map: [ "ring2" ]
    - map: [ "shoes" ]
    - map: [ "ears" ]
    - map: [ "outerClothing" ]
    - map: [ "eyes" ]
    - map: [ "belt1" ]
    - map: [ "belt2" ]
    - map: [ "id" ]
    - map: [ "keys" ]
    - map: [ "neck" ]
    - map: [ "back" ]
    - map: [ "enum.HumanoidVisualLayers.FacialHair" ]
    - map: [ "enum.HumanoidVisualLayers.Hair" ]
    - map: [ "enum.HumanoidVisualLayers.HeadSide" ]
    - map: [ "enum.HumanoidVisualLayers.HeadTop" ]
    - map: [ "enum.HumanoidVisualLayers.Tail" ]
    - map: [ "mask" ]
    - map: [ "head" ]
    - map: [ "pocket1" ]
    - map: [ "pocket2" ]
  - type: HumanoidAppearance
    species: CP14Human
  - type: Body
    prototype: CP14Human
    requiredLegs: 2