- type: entity
  save: false
  id: CP14MobDamageable
  categories: [ ForkFiltered ]
  abstract: true
  components:
  - type: Damageable
    damageContainer: CP14Biological
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTypeTrigger
        damageType: Blunt
        damage: 400
      behaviors:
      - !type:GibBehavior { }
    - trigger:
        !type:DamageTypeTrigger
        damageType: Heat
        damage: 1500
      behaviors:
      - !type:SpawnEntitiesBehavior
        spawnInContainer: true
        spawn:
          CP14Ash1:
            min: 2
            max: 3
      - !type:BurnBodyBehavior { }
      - !type:PlaySoundBehavior
        sound:
          collection: MeatLaserImpact
  - type: Stamina
  - type: MobState
  - type: MobThresholds
    thresholds:
      0: Alive
      100: Critical
      200: Dead
  - type: MobStateActions
    actions:
      Critical:
      - ActionCritSuccumb
      - ActionCritFakeDeath
      - ActionCritLastWords
  - type: Deathgasp
  - type: HealthExaminable
    examinableTypes:
    - Blunt
    - Slash
    - Piercing
    - Heat
    - Shock
    - Cold
    - Caustic
    - CP14ManaDepletion
  - type: DamageOnHighSpeedImpact
    damage:
      types:
        Blunt: 5
    soundHit:
      path: /Audio/Effects/hit_kick.ogg
  - type: Pullable

# Used for mobs that need food & water for life
- type: entity
  id: CP14MobStarving
  abstract: true
  categories: [ ForkFiltered ]
  components:
  - type: Hunger
    starvationDamage:
      types:
        Cold: 0.25
        Bloodloss: 0.25
  - type: Thirst

- type: entity
  id: CP14MobMagical
  abstract: true
  categories: [ ForkFiltered ]
  components:
  - type: CP14MagicCasterSlowdown
  - type: CP14MagicEnergyContainer
    magicAlert: CP14MagicEnergy
    maxEnergy: 100
    energy: 100
    unsafeSupport: true
  - type: CP14MagicEnergyDraw
    energy: 1
    delay: 3 # 5m to full restore
  - type: CP14MagicUnsafeDamage
  - type: CP14MagicUnsafeSleep
  - type: CP14AuraImprint