using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CP14.UserInterface.Systems.Skill.Window;

[GenerateTypedNameReferences]
public sealed partial class CP14SkillWindow : DefaultWindow
{
    public CP14SkillWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
