- type: entity
  parent: CP14ClothingPantsBase
  id: CP14ClothingPantsDressBlack
  name: black dress
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Pants/Dress/black.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Pants/Dress/black.rsi

- type: entity
  parent: CP14ClothingPantsBase
  id: CP14ClothingPantsDressBlue
  name: blue dress
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Pants/Dress/blue.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Pants/Dress/blue.rsi

- type: entity
  parent: CP14ClothingPantsBase
  id: CP14ClothingPantsDressBrown
  name: brown dress
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Pants/Dress/brown.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Pants/Dress/brown.rsi

- type: entity
  parent: CP14ClothingPantsBase
  id: CP14ClothingPantsDressGreen
  name: green dress
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Pants/Dress/green.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Pants/Dress/green.rsi

- type: entity
  parent: CP14ClothingPantsBase
  id: CP14ClothingPantsDressGreenBelt
  name: green belt dress
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Pants/Dress/green_belt.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Pants/Dress/green_belt.rsi

- type: entity
  parent: CP14ClothingPantsDressGreenBelt
  id: CP14ClothingPantsDressGreenBelt2
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Pants/Dress/green_belt2.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Pants/Dress/green_belt2.rsi

- type: entity
  parent: CP14ClothingPantsBase
  id: CP14ClothingPantsDressRed
  name: red dress
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Pants/Dress/red.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Pants/Dress/red.rsi

- type: entity
  parent: CP14ClothingPantsBase
  id: CP14ClothingPantsDressYellow
  name: yellow dress
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Pants/Dress/yellow.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Pants/Dress/yellow.rsi

- type: entity
  parent: CP14ClothingPantsBase
  id: CP14ClothingPantsSouthernMagician
  name: southern magician's dress
  description: A traditional southern mage skirt, rather loose.
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Pants/Dress/yellow_magician_dress.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Pants/Dress/yellow_magician_dress.rsi