name: "Запросить контент или предложить идею"
description: "Предложите контент, механику или другие изменения, которые вы считаете принесут пользу проекту."
labels: [suggestion]
type: Suggestion
body:
  - type: textarea
    id: concept
    attributes:
      label: Концепция
      placeholder: |
        В чем заключается ваше предложение?

        Пример:
        Добавить новую роль ____, которая выполняет задачи связанные с ____ и ____. 
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Зачем это нужно? 
      placeholder: |
        Объясните, как это улучшит игру, или какие проблемы это исправит. Предложения без должной аргументации и причины добавления могут быть закрыты.

        Пример:
        На текущий момент, в раунде часто происходит ____, из за чего не хватает ____. Эта роль могла бы закрыть эту потребность, выполняя _____. 
    validations:
      required: true
