- type: gameMapPool
  id: DefaultMapPool
  maps:
   - Dev
#  - Atlas
#  - Bagel
#  - Box
#  - Cluster
#  - Core
#  - Fland
#  - Marathon
#  - Meta
#  - Oasis
#  - Omega
#  - Origin
#  - Saltern
#  - Packed
#  - Reach
  #- Train <- return after station anchoring PR is finished and merged
