- type: entity
  abstract: true
  parent: Clothing
  id: CP14ClothingShirtBase
  description: Pleasant to the touch material, in a comfortable loose shirt shape.
  categories: [ ForkFiltered ]
  components:
  - type: Clothing
    equipDelay: 1
    unequipDelay: 1
    slots:
    - shirt
  - type: Sprite
    state: icon
  - type: Butcherable
    butcheringType: Knife
    spawned:
    - id: CP14Cloth1
      amount: 2
