- type: entity
  parent: CP14ClothingShirtBase
  id: CP14ClothingShirtCottonBlue
  name: cotton blue shirt
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Shirt/Roles/General/blue.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Shirt/Roles/General/blue.rsi

- type: entity
  parent: CP14ClothingShirtBase
  id: CP14ClothingShirtCottonBlack
  name: cotton black shirt
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Shirt/Roles/General/black.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Shirt/Roles/General/black.rsi

- type: entity
  parent: CP14ClothingShirtBase
  id: CP14ClothingShirtCottonPurple
  name: cotton purple shirt
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Shirt/Roles/General/purple.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Shirt/Roles/General/purple.rsi

- type: entity
  parent: CP14ClothingShirtBase
  id: CP14ClothingShirtCottonRed
  name: cotton red shirt
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Shirt/Roles/General/red.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Shirt/Roles/General/red.rsi

- type: entity
  parent: CP14ClothingShirtBase
  id: CP14ClothingShirtCottonWhite
  name: cotton white shirt
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Shirt/Roles/General/white.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Shirt/Roles/General/white.rsi

- type: entity
  parent: CP14ClothingShirtBase
  id: CP14ClothingShirtCottonYellow
  name: cotton yellow shirt
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Shirt/Roles/General/yellow.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Shirt/Roles/General/yellow.rsi

- type: entity
  parent: CP14ClothingShirtBase
  id: CP14ClothingShirtMercenary
  name: mercenary shirt
  description: A mercenary's colourful shirt.
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Shirt/Roles/General/mercenary.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Shirt/Roles/General/mercenary.rsi

- type: entity
  parent: CP14ClothingShirtBase
  id: CP14ClothingShirtYellowWizard
  name: yellow wizard shirt
  description: A loose magician's shirt, comfortable and nice looking.
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Shirt/Roles/General/yellow_wizard.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Shirt/Roles/General/yellow_wizard.rsi
