- type: Tag
  id: CP14RecipeSewing

- type: Tag
  id: CP14RecipeCooking

- type: Tag
  id: CP14RecipeWorkbench

- type: Tag
  id: CP14RecipeAnvil

- type: Tag
  id: CP14RecipeMeltingFurnace

- type: Tag
  id: CP14RecipeLeatherWorking

# Vampire
- type: Tag
  id: CP14RecipeVampireDevourers

- type: Tag
  id: CP14RecipeVampireUnnameable

- type: Tag
  id: CP14RecipeVampireNightChildrens
  