- type: modularPart
  id: BaseBladeBloodFlower
  modifiers:
  - !type:EditDamageableModifier
    multiplier: 0.95
  - !type:EditSharpened
    sharpnessDamageMultiplier: 0.95
  - !type:EditMeleeWeapon
    damageMultiplier: 1.1
    attackRateMultiplier: 0.9
  - !type:EditIncreaseDamageOnWield
    damageMultiplier: 1.1

- type: modularPart
  id: BaseBladeChromiumslime
  modifiers:
  - !type:EditDamageableModifier
    multiplier: 1.05
  - !type:EditSharpened
    sharpnessDamageMultiplier: 1.05
  - !type:EditMeleeWeapon
    damageMultiplier: 0.9
    attackRateMultiplier: 1.1
  - !type:EditIncreaseDamageOnWield
    damageMultiplier: 0.9

- type: modularPart
  id: BaseBladeDayflin
  modifiers:
  - !type:EditDamageableModifier
    multiplier: 1.15
  - !type:EditSharpened
    sharpnessDamageMultiplier: 1.15
  - !type:EditMeleeWeapon
    damageMultiplier: 0.7
    attackRateMultiplier: 2
  - !type:EditIncreaseDamageOnWield
    damageMultiplier: 0.7