using System.Numerics;
using Content.Client._CP14.UserInterface.Systems.NodeTree;
using Content.Shared._CP14.DemiplaneTraveling;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._CP14.DemiplaneTraveling;

[GenerateTypedNameReferences]
public sealed partial class CP14DemiplaneMapWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly ILogManager _log = default!;

    private CP14DemiplaneMapUiState? _cachedState;

    private ISawmill Sawmill { get; init; }
    public CP14DemiplaneMapWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Sawmill = _log.GetSawmill("cp14_demiplane_map_window");

        GraphControl.OnOffsetChanged += offset =>
        {
            ParallaxBackground.Offset = -offset * 0.25f + new Vector2(1000, 1000); //hardcoding is bad
        };
    }

    public void UpdateState(CP14DemiplaneMapUiState state)
    {
        _cachedState = state;

        HashSet<CP14NodeTreeElement> nodeTreeElements = new();
        foreach (var node in state.Nodes)
        {

            if (node.Start)
            {
                var startElement = new CP14NodeTreeElement(
                    nodeKey: node.NodeKey,
                    gained: true,
                    active: true,
                    node.UiPosition * 100,
                    icon: new SpriteSpecifier.Rsi(new ResPath("_CP14/Interface/NodeTree/demiplane_map.rsi"), "center"));
                nodeTreeElements.Add(startElement);
            }
            else
            {
                _prototype.TryIndex(node.Location, out var location);

                var treeElement = new CP14NodeTreeElement(
                    nodeKey: node.NodeKey,
                    gained: false,
                    active: true,
                    node.UiPosition * 100,
                    icon: location?.Icon);
                nodeTreeElements.Add(treeElement);
            }
        }
        GraphControl.UpdateState(
            new CP14NodeTreeUiState(
                nodeTreeElements,
                edges: state.Edges,
                frameIcon: new SpriteSpecifier.Rsi(new ResPath("/Textures/_CP14/Interface/NodeTree/demiplane_map.rsi"), "frame"),
                hoveredIcon: new SpriteSpecifier.Rsi(new ResPath("/Textures/_CP14/Interface/NodeTree/demiplane_map.rsi"), "hovered"),
                selectedIcon: new SpriteSpecifier.Rsi(new ResPath("/Textures/_CP14/Interface/NodeTree/demiplane_map.rsi"), "selected"),
                learnedIcon: new SpriteSpecifier.Rsi(new ResPath("/Textures/_CP14/Interface/NodeTree/demiplane_map.rsi"), "learned"),
                lineColor: new Color(172, 102, 190)
                )
            );
    }
}
