- type: job
  id: CP14Alchemist
  name: cp14-job-name-alchemist
  description: cp14-job-desc-alchemist
  playTimeTracker: CP14JobAlchemist
  startingGear: CP14AlchemistGear
  icon: "CP14JobIconAlchemist"
  supervisors: cp14-job-supervisors-command
  special:
  - !type:CP14AddSkillSpecial
    skills:
    - Alchemy

- type: startingGear
  id: CP14AlchemistGear
  equipment:
    belt1: CP14WalletFilledTest
    keys: CP14KeyRingAlchemist