using Content.Shared._CP14.Configuration;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CP14.Options;

[GenerateTypedNameReferences]
public sealed partial class CP14OptionsMenuMainTab : Control
{
    public CP14OptionsMenuMainTab()
    {
        RobustXamlLoader.Load(this);

        Control.AddOptionCheckBox(CP14ConfigVars.WaveShaderEnabled, WaveShaderEnabled);
        Control.AddOptionCheckBox(CCVars.PostProcess, PostProcessCheckBox);

        Control.Initialize();
    }
}
