- type: entity
  id: CP14BaseRoof
  categories: [ ForkFiltered ]
  abstract: true
  name: roof
  description: A roof over your head to protect you from the heat of the sun or the weather.
  placement:
    mode: SnapgridCenter
  components:
  - type: PlacementReplacement
    key: CP14Roof
  - type: Physics
    bodyType: Static
    canCollide: false
  - type: Transform
    anchored: true
  - type: BlockWeather
  - type: CP14Roof
  - type: Sprite
    drawdepth: Effects
    sprite: _CP14/Structures/Roof/test.rsi
  - type: Icon
    sprite: _CP14/Structures/Roof/test.rsi
    state: full
  - type: IconSmooth
    key: CP14roof
    base: roof

- type: entity
  parent: 
  - CP14BaseRoof
  - CP14BaseFlammableSpreading
  id: CP14RoofWooden
  name: wooden roof
  components:
  - type: Sprite
    sprite: _CP14/Structures/Roof/wooden.rsi
  - type: Icon
    sprite: _CP14/Structures/Roof/wooden.rsi
  - type: Damageable
    damageContainer: Inorganic
    damageModifierSet: Wood
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 100
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          collection: WoodDestroy
      - !type:SpawnEntitiesBehavior
        spawn:
          CP14WoodenPlanks1:
            min: 1
            max: 1
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: Construction
    graph: CP14RoofWooden
    node: CP14RoofWooden

- type: entity
  parent: 
  - CP14BaseRoof
  id: CP14RoofStone
  name: stone roof
  components:
  - type: Sprite
    sprite: _CP14/Structures/Roof/stone.rsi
  - type: Icon
    sprite: _CP14/Structures/Roof/stone.rsi
  - type: Damageable
    damageContainer: StructuralInorganic
    damageModifierSet: Rock
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 150
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          path: /Audio/Effects/break_stone.ogg
          params:
            volume: -6
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: Construction
    graph: CP14RoofStone
    node: CP14RoofStone

- type: entity
  parent: 
  - CP14BaseRoof
  id: CP14RoofRemover
  name: roof remover debug
  components:
  - type: Sprite
    sprite: _CP14/Structures/Roof/stone.rsi
  - type: Icon
    sprite: _CP14/Structures/Roof/stone.rsi
  - type: TimedDespawn
    lifetime: 2
    