- type: entity
  id: CP14BaseRoof
  categories: [ ForkFiltered ]
  abstract: true
  name: roof
  description: A roof over your head to protect you from the heat of the sun or the weather.
  placement:
    mode: SnapgridCenter
    snap:
    - Wall
  components:
  - type: PlacementReplacement
    key: roof
  - type: Clickable
  - type: Physics
    bodyType: Static 
  - type: Transform
    anchored: true
  - type: BlockWeather
  - type: CP14Roof
  - type: Sprite
    drawdepth: Effects
    sprite: _CP14/Structures/Roof/test.rsi
  - type: Icon
    sprite: _CP14/Structures/Roof/test.rsi
    state: full
  - type: IconSmooth
    key: CP14roof
    base: roof

- type: entity
  parent: CP14BaseRoof
  id: CP14RoofWooden
  name: wooden roof
  components:
  - type: Sprite
    sprite: _CP14/Structures/Roof/wooden.rsi
  - type: Icon
    sprite: _CP14/Structures/Roof/wooden.rsi