# Tile structure:
# Base indedstructable stone tile
# - Dirt
#   - Grass variants
# - Gravel
# - Sand
# - other natural tiles
# - Fundament
#   - Wood planks
#   - Stonebricks
#   - other produced tiles

- type: tile
  editorHidden: false
  id: CP14FloorBase
  name: cp14-tiles-base
  sprite: /Textures/_CP14/Tiles/Stone/cave.png
  variants: 14
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  edgeSpritePriority: -1
  edgeSprites:
    SouthEast: /Textures/_CP14/Tiles/Stone/single_edge_SE.png
    NorthEast: /Textures/_CP14/Tiles/Stone/single_edge_NE.png
    NorthWest: /Textures/_CP14/Tiles/Stone/single_edge_NW.png
    SouthWest: /Textures/_CP14/Tiles/Stone/single_edge_SW.png
    South: /Textures/_CP14/Tiles/Stone/double_edge_S.png
    East: /Textures/_CP14/Tiles/Stone/double_edge_E.png
    North: /Textures/_CP14/Tiles/Stone/double_edge_N.png
    West: /Textures/_CP14/Tiles/Stone/double_edge_W.png
  baseTurf: CP14FloorBase #Recursivle indestructible
  isSubfloor: true
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true
  color: "#38373b"
  indestructible: true