- type: tile
  editorHidden: false
  id: CP14FloorFoundation
  name: cp14-tiles-foundation
  sprite: /Textures/_CP14/Tiles/Foundation/foundation.png
  variants: 2
  placementVariants:
  - 1.0
  - 1.0
  edgeSpritePriority: 1
  edgeSprites:
    SouthEast: /Textures/_CP14/Tiles/Foundation/single_edge.png
    NorthEast: /Textures/_CP14/Tiles/Foundation/single_edge.png
    NorthWest: /Textures/_CP14/Tiles/Foundation/single_edge.png
    SouthWest: /Textures/_CP14/Tiles/Foundation/single_edge.png
    South: /Textures/_CP14/Tiles/Foundation/double_edge_down.png
    East: /Textures/_CP14/Tiles/Foundation/double_edge_right.png
    North: /Textures/_CP14/Tiles/Foundation/double_edge_top.png
    West: /Textures/_CP14/Tiles/Foundation/double_edge_left.png
  baseTurf: CP14FloorBase
  isSubfloor: true
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: false

- type: tile
  editorHidden: false
  id: CP14FloorWoodPlanks
  name: cp14-tiles-woodplanks
  sprite: /Textures/_CP14/Tiles/woodplanks.png
  variants: 4
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  baseTurf: CP14FloorFoundation
  isSubfloor: false
  footstepSounds:
    collection: FootstepWood
  heatCapacity: 10000
  weather: false
  burnedTile: CP14FloorWoodPlanksBurned

- type: tile
  editorHidden: false
  id: CP14FloorWoodPlanksBroken
  name: cp14-tiles-woodplanks-broken
  sprite: /Textures/_CP14/Tiles/woodplanks_broken.png
  variants: 4
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  baseTurf: CP14FloorFoundation
  isSubfloor: false
  footstepSounds:
    collection: FootstepWood
  heatCapacity: 10000
  weather: false
  burnedTile: CP14FloorWoodPlanksBurned

- type: tile
  editorHidden: false
  id: CP14FloorWoodPlanksBurned
  name: cp14-tiles-woodplanks-burned
  sprite: /Textures/_CP14/Tiles/woodplanks_burned.png
  variants: 4
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  baseTurf: CP14FloorFoundation
  isSubfloor: false
  footstepSounds:
    collection: FootstepWood
  heatCapacity: 10000

- type: tile
  editorHidden: false
  id: CP14FloorWoodPlanksBig
  name: cp14-tiles-woodplanks-big
  sprite: /Textures/_CP14/Tiles/woodplanks_big.png
  variants: 4
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  baseTurf: CP14FloorFoundation
  isSubfloor: false
  footstepSounds:
    collection: FootstepWood
  heatCapacity: 10000
  weather: false
  burnedTile: CP14FloorWoodPlanksBigBurned

- type: tile
  editorHidden: false
  id: CP14FloorWoodPlanksBigBroken
  name: cp14-tiles-woodplanks-big-broken
  sprite: /Textures/_CP14/Tiles/woodplanks_big_broken.png
  variants: 4
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  baseTurf: CP14FloorFoundation
  isSubfloor: false
  footstepSounds:
    collection: FootstepWood
  heatCapacity: 10000
  weather: false
  burnedTile: CP14FloorWoodPlanksBigBurned

- type: tile
  editorHidden: false
  id: CP14FloorWoodPlanksBigBurned
  name: cp14-tiles-woodplanks-big-burned
  sprite: /Textures/_CP14/Tiles/woodplanks_big_burned.png
  variants: 4
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  baseTurf: CP14FloorFoundation
  isSubfloor: false
  footstepSounds:
    collection: FootstepWood
  heatCapacity: 10000
  weather: false

- type: tile
  editorHidden: false
  id: CP14FloorStonebricks
  name: cp14-tiles-stonebricks
  sprite: /Textures/_CP14/Tiles/stonebricks.png
  variants: 1
  placementVariants:
  - 1.0
  baseTurf: CP14Floorfundament
  isSubfloor: false
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: false

- type: tile
  editorHidden: false
  id: CP14FloorStonebricksSmallCarved1
  name: cp14-tiles-stonebricks-small-carved1
  sprite: /Textures/_CP14/Tiles/stonebricks_small_carved_1.png
  variants: 1
  placementVariants:
  - 1.0
  baseTurf: CP14FloorFoundation
  isSubfloor: false
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: false

- type: tile
  editorHidden: false
  id: CP14FloorStonebricksSmallCarved2
  name: cp14-tiles-stonebricks-small-carved2
  sprite: /Textures/_CP14/Tiles/stonebricks_small_carved_2.png
  variants: 1
  placementVariants:
  - 1.0
  baseTurf: CP14FloorFoundation
  isSubfloor: false
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: false

- type: tile
  editorHidden: false
  id: CP14FloorStonebricksSquareCarved
  name: cp14-tiles-stonebricks-square-carved
  sprite: /Textures/_CP14/Tiles/stonebricks_square_carved.png
  variants: 1
  placementVariants:
  - 1.0
  baseTurf: CP14FloorFoundation
  isSubfloor: false
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: false