using Content.Shared._CP14.TravelingStoreShip;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._CP14.TravelingStoreShip;

[GenerateTypedNameReferences]
public sealed partial class CP14StoreProductControl : Control
{
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    private readonly CP14StoreBuyPositionPrototype _recipePrototype;

    public CP14StoreProductControl(CP14StoreUiProductEntry entry)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _recipePrototype = _prototype.Index(entry.ProtoId);

        ProductName.Text = Loc.GetString(_recipePrototype.ID);
    }
}
