using Content.Shared._CP14.Cargo;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._CP14.TravelingStoreShip;

[GenerateTypedNameReferences]
public sealed partial class CP14StoreWindow : DefaultWindow
{
    public CP14StoreWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void UpdateUI(CP14StoreUiState state)
    {
        UpdateProducts(state);
    }

    private void UpdateProducts(CP14StoreUiState state)
    {
        foreach (var product in state.ProductsBuy)
        {
            var control = new CP14StoreProductControl(product);
            control.ProductButton.OnPressed += _ =>
            {
                SelectProduct(product);
            };
            BuyPositions.AddChild(control);
        }
    }

    private void SelectProduct(CP14StoreUiProductEntry? entry)
    {
        SelectedName.Text = entry is null ? string.Empty : $"[bold]{entry.Value.Name}[/bold]";
        SelectedDesc.Text = entry is null ? string.Empty : entry.Value.Desc;
    }
}
