using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stalker.Discord;
[GenerateTypedNameReferences]
public sealed partial class DiscordAuthGui : Control
{
    [Dependency] private readonly IClientConsoleHost _consoleHost = default!;
    private const string DiscordLink = "https://discord.com/invite/Y6fdHySWBD";

    public DiscordAuthGui()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);

        QuitButton.OnPressed += (_) =>
        {
            _consoleHost.ExecuteCommand("quit");
        };

        OpenUrlButton.OnPressed += (_) =>
        {
            IoCManager.Resolve<IUriOpener>().OpenUri(DiscordLink);
        };
    }
}
