- type: entity
  parent: CP14ClothingHeadBase
  id: CP14ClothingHeadCaptainCap
  name: captain's cap
  description: No, look how handsome he is!
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Head/Roles/Captain/cap.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Head/Roles/Captain/cap.rsi