using System.Linq;
using System.Numerics;
using Content.Client._CP14.UserInterface.Systems.NodeTree;
using Content.Shared._CP14.Trading;
using Content.Shared._CP14.Trading.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._CP14.Trading;

[GenerateTypedNameReferences]
public sealed partial class CP14TradingPlatformWindow : DefaultWindow
{
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;

    private CP14TradingPlatformUiState? _cacheState;

    private IEnumerable<CP14TradingPositionPrototype> _allPositions = [];
    private IEnumerable<CP14TradingFactionPrototype> _allFactions = [];

    private ProtoId<CP14TradingFactionPrototype>? _selectedFaction;

    public CP14TradingPlatformWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        CacheSkillProto();
        _proto.PrototypesReloaded += _ => CacheSkillProto();
        _selectedFaction = _allFactions.First();

        GraphControl.OnOffsetChanged += offset =>
        {
            ParallaxBackground.Offset = -offset * 0.25f + new Vector2(1000, 1000); //hardcoding is bad
        };
        GraphControl.OnNodeSelected += SelectNode;
    }

    private void SelectNode(CP14NodeTreeElement? node)
    {

    }

    private void DeselectNode()
    {
        Name.Text = string.Empty;
        Description.Text = string.Empty;
        LocationView.Texture = null;
        EjectButton.Disabled = true;
    }

    private void CacheSkillProto()
    {
        _allPositions = _proto.EnumeratePrototypes<CP14TradingPositionPrototype>();
        _allFactions = _proto.EnumeratePrototypes<CP14TradingFactionPrototype>().OrderBy(tree => Loc.GetString(tree.Name));
    }

    public void UpdateState(CP14TradingPlatformUiState state)
    {
        _cacheState = state;

        UpdateGraphControl();
    }

    private void UpdateGraphControl()
    {
        if (_cacheState is null)
            return;

        HashSet<CP14NodeTreeElement> nodeTreeElements = new();
        var edges = new HashSet<(string, string)>();
        foreach (var position in _allPositions)
        {
            if (position.Faction != _selectedFaction)
                continue;

            var node = new CP14NodeTreeElement(position.ID, _cacheState.UnlockedPositions.Contains(position), false, position.UiPosition * 50, position.Icon);
            nodeTreeElements.Add(node);
            if (position.Prerequisite != null)
            {
                edges.Add((position.Prerequisite, position.ID));
            }
        }

        GraphControl.UpdateState(
            new CP14NodeTreeUiState(
                nodeTreeElements,
                edges: edges,
                frameIcon: new SpriteSpecifier.Rsi(
                    new ResPath("/Textures/_CP14/Interface/NodeTree/demiplane_map.rsi"),
                    "frame"),
                hoveredIcon: new SpriteSpecifier.Rsi(
                    new ResPath("/Textures/_CP14/Interface/NodeTree/demiplane_map.rsi"),
                    "hovered"),
                selectedIcon: new SpriteSpecifier.Rsi(
                    new ResPath("/Textures/_CP14/Interface/NodeTree/demiplane_map.rsi"),
                    "selected"),
                learnedIcon: new SpriteSpecifier.Rsi(
                    new ResPath("/Textures/_CP14/Interface/NodeTree/demiplane_map.rsi"),
                    "learned"),
                activeLineColor: new Color(172, 102, 190),
                lineColor: new Color(83, 40, 121)
            )
        );

        //Faction tabs update
        TreeTabsContainer.RemoveAllChildren();
        foreach (var faction in _allFactions)
        {
            var factionButton = new CP14TradingFactionButtonControl(
                faction.Color,
                Loc.GetString(faction.Name),
                _cacheState.Reputation.GetValueOrDefault(faction.ID, 0f));

            factionButton.OnPressed += () =>
            {
                SelectFaction(faction);
            };

            TreeTabsContainer.AddChild(factionButton);
        }
    }

    private void SelectFaction(CP14TradingFactionPrototype faction)
    {
        _selectedFaction = faction;
        //ParallaxBackground.ParallaxPrototype = faction.ParallaxBackground;
        TreeName.Text = Loc.GetString(faction.Name);
        UpdateGraphControl();
    }
}
