using Content.Client._CP14.UserInterface;
using Content.Client._CP14.Workbench;
using Content.Shared._CP14.Trading.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._CP14.Trading;

[GenerateTypedNameReferences]
public sealed partial class CP14SellingRequestControl : Control
{
    [Dependency] private readonly IPrototypeManager _proto = default!;

    public event Action? OnSellAttempt;

    public CP14SellingRequestControl(ProtoId<CP14TradingRequestPrototype> request)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        if (!_proto.TryIndex(request, out var indexedRequest))
            return;

        //Requirements
        ItemRequirements.RemoveAllChildren();
        foreach (var requirement in indexedRequest.Requirements)
        {
            ItemRequirements.AddChild(new CP14WorkbenchRequirementControl(requirement));
        }

        //Coin reward
        PriceHolder.RemoveAllChildren();
        PriceHolder.AddChild(new CP14PriceControl(indexedRequest.AdditionalReward));

        //Rep reward
        Reputation.Text = indexedRequest.ReputationReward.ToString("0.00");
    }
}
