using Content.Shared._CP14.Trading;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._CP14.Trading;

[GenerateTypedNameReferences]
public sealed partial class CP14TradingPlatformWindow : DefaultWindow
{
    [Dependency] private readonly IGameTiming _timing = default!;

    public CP14TradingPlatformWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void UpdateUI(CP14TradingPlatformUiState state)
    {
    }

    private void UpdateProducts(CP14TradingPlatformUiState state)
    {
    }

    private void SelectProduct(CP14TradingProductEntry? entry)
    {
    }
}
