using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CP14.Trading;

[GenerateTypedNameReferences]
public sealed partial class CP14TradingFactionButtonControl : Control
{
    public event Action? OnPressed;

    public CP14TradingFactionButtonControl(Color color, string label, float skillpoints)
    {
        RobustXamlLoader.Load(this);

        ColorPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = color };
        if (skillpoints > 0)
        {
            SkillPointImage.Visible = true;
            SkillTreeLabel.Text = $"{skillpoints} {label}";
        }
        else
        {
            SkillPointImage.Visible = false;
            SkillTreeLabel.Text = $"{label}";
        }

        MainButton.OnPressed += args => OnPressed?.Invoke();
    }
}
