# Clear to black.
[[layers]]
type = "clear"
color = "#000000"

# Bright background nebula stars.
[[layers]]
type = "points"
closecolor = "#aa47ad"
count = 1000
seed = 4810
mask = true
masknoise_type = "fbm"
maskoctaves = 4
maskpersistence = "0.5"
maskpower = "0.35"
masklacunarity = "1.5"
maskfrequency = "3"
maskthreshold = "0.37"
maskseed = 3551

# Bright background nebula stars, dim edge.
[[layers]]
type = "points"
closecolor = "#41244a"
pointsize = 2
count = 1000
seed = 4810
mask = true
masknoise_type = "fbm"
maskoctaves = 4
maskpersistence = "0.5"
maskpower = "0.35"
masklacunarity = "1.5"
maskfrequency = "3"
maskthreshold = "0.37"
maskseed = 3551

# Couple of bright pink stars.
[[layers]]
type = "points"
closecolor = "#ff63ef"
count = 30
seed = 9019

# And their dim edge.
[[layers]]
type = "points"
closecolor = "#301a43"
pointsize = 2
count = 30
seed = 9019

# Colour-to-alpha.
[[layers]]
type = "toalpha"

