- type: entity
  parent: BaseMaterialDoorNavMap
  id: CP14BaseDoor
  categories: [ ForkFiltered ]
  abstract: true
  components:
  - type: Sprite
    drawdepth: Mobs
  - type: Door
    bumpOpen: false
    clickOpen: true
    closeTimeOne: 0
    closeTimeTwo: 0
    openTimeOne: 0
    openTimeTwo: 0
    closedDrawDepth: Mobs
    openDrawDepth: Mobs
  - type: Lock
    locked: false
  - type: PlacementReplacement
    key: walls