- type: entity
  parent: BaseMaterialDoorNavMap
  id: CP14BaseDoor
  categories: [ ForkFiltered ]
  abstract: true
  components:
  - type: Sprite
    drawdepth: Mobs
  - type: Door
    bumpOpen: false
    clickOpen: true
    closeTimeOne: 0
    closeTimeTwo: 0
    openTimeOne: 0
    openTimeTwo: 0
    closedDrawDepth: Mobs
    openDrawDepth: Mobs
  - type: Lock
    locked: false
  - type: PlacementReplacement
    key: walls
  - type: CP14DoorInteractionPopup
    interactSound:
      collection: CP14Doorknob
      params:
        variation: 0.03
        volume: -5
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-0.49,-0.49,0.49,0.49"
        density: 100
        mask:
        - FullTileMask
        layer:
        - AirlockLayer
        - Impassable
