- type: entity
  parent: BaseStructure
  id: CP14BaseFence
  categories: [ ForkFiltered ]
  abstract: true
  components:
  - type: MeleeSound
    soundGroups:
      Brute:
        path:
          "/Audio/Weapons/boxingpunch1.ogg"
  - type: Sprite
    drawdepth: Mobs
  - type: Physics
    bodyType: Static
  - type: Transform
    anchored: true
  - type: PlacementReplacement
    key: walls

- type: entity
  parent: CP14BaseFence
  id: CP14BaseFenceStraight
  abstract: true
  components:
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-0.49,-0.49,0.49,-0.29"
        density: 1000
        mask:
        - FullTileMask
        layer:
        - MidImpassable
        - LowImpassable

- type: entity
  parent: CP14BaseFence
  id: CP14BaseFenceCorner
  abstract: true
  components:
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-0.49,-0.49,0.49,-0.29"
        density: 1000
        mask:
        - TableMask
        layer:
        - TableLayer
      fix2:
        shape:
          !type:PhysShapeAabb
          bounds: "0.29,-0.49,0.49,0.49"
        density: 1000
        mask:
        - TableMask
        layer:
        - MidImpassable
        - LowImpassable

- type: entity
  parent: CP14BaseFenceStraight
  id: CP14BaseFenceDoor
  abstract: true
  components:
  - type: InteractionOutline
  - type: Appearance
  - type: Door
    openSpriteState: door_opened
    closedSpriteState: door_closed
    canPry: false
    occludes: false
    changeAirtight: false
    bumpOpen: false
    clickOpen: true
    canCrush: false
    closeTimeOne: 0
    closeTimeTwo: 0
    openTimeOne: 0
    openTimeTwo: 0
    closedDrawDepth: Mobs
    openDrawDepth: Mobs
    openingAnimationTime: 0
    closingAnimationTime: 0
    openSound:
      path: /Audio/Effects/door_open.ogg
    closeSound:
      path: /Audio/Effects/door_close.ogg