- type: entity
  id: CP14GatherableBase
  parent: BaseStructure
  abstract: true
  categories: [ ForkFiltered ]
  components:
  - type: Sprite
    snapCardinals: true
    drawdepth: FloorTiles
  - type: Transform
  - type: InteractionOutline
  - type: Physics
    canCollide: false
    bodyType: Static
  - type: Damageable
    damageContainer: Biological
  - type: MeleeSound
    soundGroups:
      Brute:
        collection: CP14GrassGathering
        params:
          variation: 0.03
  - type: Destructible
    thresholds:
      - trigger:
          !type:DamageTrigger
          damage: 25
        behaviors:
          - !type:DoActsBehavior
            acts: [ "Destruction" ]
      - trigger:
          !type:DamageTypeTrigger
          damageType: Cellular
          damage: 1
        behaviors:
          - !type:DoActsBehavior
            acts: [ "Destruction" ]
  - type: Fixtures
    fixtures:
      fix1:
        hard: false
        shape:
          !type:PhysShapeAabb
          bounds: "-0.45,-0.45,0.45,0.45"
        density: 60
        mask:
        - HalfWallLayer
        layer:
        - MidImpassable
        - LowImpassable
  - type: CP14PlantGatherable
    toolWhitelist:
      tags:
        - CP14HerbalGathering
      components:
        - Sharp
  - type: Appearance

- type: entity
  id: CP14GatherablePlantBase
  parent: CP14GatherableBase
  abstract: true
  components:
  - type: CP14PlantVisuals
    growthSteps: 5
    growState: "grow-"
  - type: CP14Plant
    resource: 30
    energy: 30
    growthLevel: 0
    solution: plant
  - type: SolutionContainerManager
    solutions:
      plant:
        maxVol: 200
  - type: RefillableSolution 
    solution: plant
    maxRefill: 50
  - type: ExaminableSolution
    solution: plant
  - type: SolutionContainerVisuals
    maxFillLevels: 4
    fillBaseName: liq-
    solutionName: plant

- type: entity
  id: CP14GatherablePlantBoringBase
  parent: CP14GatherablePlantBase
  abstract: true
  components:
  - type: Sprite
    sprite: _CP14/Structures/Specific/Farming/seedbed.rsi
  - type: CP14PlantMetabolizer
    metabolizerId: Base
  - type: CP14PlantEnergyFromLight
    energy: 1
    daytime: true
  - type: CP14PlantVisuals
    growthSteps: 6
  - type: CP14PlantGrowing
    energyCost: 1
    resourceCost: 1
    growthPerUpdate: 0.05 # 20 minute to full grow
  - type: CP14PlantFading
    resourcePerMinute: 0.25 #20 minute from water