- type: entity
  parent: BaseMindRoleAntag
  id: CP14MindRoleDemiplaneAntag
  name: Demiplane Antag Role
  components:
  - type: MindRole
    roleType: CP14DemiplaneAntagonist
    antagPrototype: CP14DemiplaneAntag
