- type: antag
  id: Thief
  name: roles-antag-thief-name
  antagonist: true
  setPreference: false #CP14
  objective: roles-antag-thief-objective
  guides: [ Thieves ]

- type: startingGear
  id: ThiefGear
  storage:
    back:
    - ToolboxThief
    - ClothingHandsChameleonThief
    - ThiefBeacon
