- type: job
  id: CP14Merchant
  name: cp14-job-name-merchant
  description: cp14-job-desc-merchant
  playTimeTracker: CP14JobMerchant
  startingGear: CP14MerchantGear
  icon: "CP14JobIconMerchant"
  requireAdminNotify: true
  joinNotifyCrew: true
  canBeAntag: true
  supervisors: cp14-job-supervisors-quartermaster

- type: startingGear
  id: CP14MerchantGear
  equipment:
    belt1: CP14KeyRingInnkeeper