using Content.Shared._CP14.Expeditions;

namespace Content.Server._CP14.Expeditions.Components;

/// <summary>
///
/// </summary>
[RegisterComponent, Access(typeof(CP14ExpeditionSystem))]
public sealed partial class CP14ExpeditionGeneratorComponent : Component
{
    /// <summary>
    /// Expedition map generated by this object
    /// </summary>
    [DataField]
    public EntityUid? GeneratedMap;

    public CP14ExpeditionMissionParams? MissionParams;
}
