- type: entity
  id: CP14CrystalBase
  abstract: true
  parent: BaseRock
  name: sparkling quartz
  description: Natural quartz crystals that can absorb the magical energy of the world around them. 
  categories: [ ForkFiltered ]
  components:
  - type: Sprite
    drawdepth: Mobs
    offset: 0, 0.25
    noRot: true
  - type: InteractionPopup
    interactSuccessString: popup-cp14crystal-ding
    messagePerceivedByOthers: popup-cp14crystal-ding
    interactSuccessSound:
      collection: CP14CrystalDings
      params:
        variation: 0.03
  - type: Damageable 
    damageContainer: Inorganic
    damageModifierSet: Glass
  - type: MeleeSound
    soundGroups:
      Brute:
        collection: GlassSmash
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeCircle
          radius: 0.30
        density: 60
        mask:
          - MachineMask
        layer:
          - MidImpassable
          - LowImpassable
          - BulletImpassable
          - Opaque
  - type: PointLight
    netSync: false

- type: entity
  parent: CP14CrystalBase
  id: CP14CrystalBigBase
  abstract: true
  components:
  - type: Sprite
    sprite: _CP14/Structures/Flora/Crystal/crystal_big.rsi
    layers:
      - state: big1
        shader: unshaded
        map: ["random"]
  - type: InteractionPopup
    interactSuccessSound:
      collection: CP14CrystalDings
      params:
        pitch: 0.5
        variation: 0.03
  - type: PointLight
    radius: 2
    energy: 2.5
  - type: RandomSprite
    available:
    - random:
        big0: Inherit
        big1: Inherit
        big2: Inherit

- type: entity
  parent: CP14CrystalBase
  id: CP14CrystalMediumBase
  abstract: true
  components:
  - type: Sprite
    sprite: _CP14/Structures/Flora/Crystal/crystal_medium.rsi
    layers:
      - state: medium4
        shader: unshaded
        map: ["random"]
  - type: InteractionPopup
    interactSuccessSound:
      collection: CP14CrystalDings
      params:
        pitch: 1
        variation: 0.03
  - type: PointLight
    radius: 1.5
    energy: 2
  - type: RandomSprite
    available:
    - random:
        medium0: Inherit
        medium1: Inherit
        medium2: Inherit
        medium3: Inherit
        medium4: Inherit

- type: entity
  parent: CP14CrystalBase
  id: CP14CrystalSmallBase
  abstract: true
  components:
  - type: Sprite
    sprite: _CP14/Structures/Flora/Crystal/crystal_small.rsi
    layers:
      - state: small1
        shader: unshaded
        map: ["random"]
  - type: InteractionPopup
    interactSuccessSound:
      collection: CP14CrystalDings
      params:
        pitch: 1.5
        variation: 0.03
  - type: PointLight
    radius: 1.1
    energy: 2
  - type: RandomSprite
    available:
    - random:
        small0: Inherit
        small1: Inherit
        small2: Inherit
        small3: Inherit
        small4: Inherit
        small5: Inherit
  - type: Appearance