- type: entity
  parent: BaseItem
  id: CP14BaseKey
  abstract: true
  categories: [ ForkFiltered ]
  name: key
  description: A small, intricate piece of metal that opens some locks. Don't give it to anyone!
  components: 
  - type: Tag
    tags:
    - CP14Key
  - type: Item
    size: Tiny
  - type: Sprite
    sprite: _CP14/Objects/keys.rsi
  - type: CP14Key
  - type: EmitSoundOnLand
    sound:
      path: /Audio/_CP14/Items/key_drop.ogg
      params:
        variation: 0.05

- type: entity
  parent: CP14BaseKey
  id: CP14KeyCopperBlank
  components:
  - type: Sprite
    state: key_copper
  - type: CP14Key
    lockShape:
    - 2
    - 2
    - 2

- type: entity
  parent: CP14BaseKey
  id: CP14KeyIronBlank
  components:
  - type: Sprite
    state: key_iron
  - type: CP14Key
    lockShape:
    - 2
    - 2
    - 2
    - 2
    - 2

- type: entity
  parent: CP14BaseKey
  id: CP14KeyGoldBlank
  components:
  - type: Sprite
    state: key_gold
  - type: CP14Key
    lockShape:
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2

- type: entity
  parent: CP14BaseKey
  id: CP14KeyMithrilBlank
  components:
  - type: Sprite
    state: key_mithril
  - type: CP14Key
    lockShape:
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2

- type: entity
  parent: BaseItem
  id: CP14BaseLockpick
  name: lockpick
  description: A thief's tool that, with proper skill and skill, allows you to pick any lock.
  categories: [ ForkFiltered ]
  components:
  - type: Item
    storedRotation: -90
  - type: Sprite
    sprite: _CP14/Objects/keys.rsi
    state: lockpick
  - type: CP14Lockpick
  - type: Tag
    tags:
    - CP14Lockpick

- type: entity
  parent: BaseItem
  id: CP14KeyFile
  name: key file
  description: A file, ideal for sharpening keys, and reshaping them.
  categories: [ ForkFiltered ]
  components:
  - type: Item
    storedRotation: -45
  - type: Sprite
    sprite: _CP14/Objects/keys.rsi
    state: file
  - type: CP14KeyFile