- type: entity
  id: CP14FoodCabbage
  parent: FoodInjectableBase
  categories: [ ForkFiltered ]
  name: cabbage
  description: Green edible ball.
  components:
  - type: Item
    size: Normal
  - type: FlavorProfile
    flavors:
      - cabbage
  - type: Sprite
    sprite: _CP14/Objects/Flora/Farm/cabbage.rsi
    layers:
      - state: base1
        map: [ "random" ]
  - type: RandomSprite
    available:
      - random:
          base1: ""
          base2: ""
          base3: ""
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 12
        reagents:
        - ReagentId: Nutriment
          Quantity: 10
        - ReagentId: Vitamin
          Quantity: 1
  - type: SliceableFood
    count: 4
    sliceTime: 1.5
    slice: CP14FoodCabbageSlice
  - type: Tag
    tags:
    - CP14FarmFood

- type: entity
  id: CP14FoodCabbageSlice
  parent: FoodInjectableBase
  categories: [ ForkFiltered ]
  name: cabbage leaf
  description: Time to make green salads
  components:
  - type: Item
    size: Tiny
  - type: FlavorProfile
    flavors:
      - cabbage
  - type: Sprite
    sprite: _CP14/Objects/Flora/Farm/cabbage.rsi
    layers:
      - state: slice1
        map: [ "random" ]
  - type: RandomSprite
    available:
      - random:
          slice1: ""
          slice2: ""
          slice3: ""
          slice4: ""
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 3 # 1/4 cabbage
        reagents:
        - ReagentId: Nutriment
          Quantity: 2.5
        - ReagentId: Vitamin
          Quantity: 0.25
  - type: FoodSequenceElement
    entries:
      Sandwich: CP14CabbageSandwich

- type: entity
  id: CP14FoodPumpkin
  parent: FoodInjectableBase
  categories: [ ForkFiltered ]
  name: pumpkin
  description: Big, cool pumpkin.
  components:
  - type: Item
    size: Normal
  - type: FlavorProfile
    flavors:
      - pumpkin
  - type: Sprite
    sprite: _CP14/Objects/Flora/Farm/pumpkin.rsi
    layers:
      - state: base1
        map: [ "random" ]
  - type: RandomSprite
    available:
      - random:
          base1: ""
          base2: ""
          base3: ""
          base4: ""
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 30
        reagents:
        - ReagentId: PumpkinFlesh
          Quantity: 20
        - ReagentId: Vitamin
          Quantity: 5
  - type: SliceableFood
    count: 5
    sliceTime: 2
    slice: CP14FoodPumpkinSlice
  - type: Tag
    tags:
    - CP14FarmFood

- type: entity
  id: CP14FoodPumpkinSlice
  parent: FoodInjectableBase
  categories: [ ForkFiltered ]
  name: pumpkin slice
  description: Pumpkin! # TODO
  components:
  - type: Item
    size: Tiny
  - type: FlavorProfile
    flavors:
      - pumpkin
  - type: Sprite
    sprite: _CP14/Objects/Flora/Farm/pumpkin.rsi
    layers:
      - state: slice1
        map: [ "random" ]
  - type: RandomSprite
    available:
      - random:
          slice1: ""
          slice2: ""
          slice3: ""
          slice4: ""
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 6 # 1/5 pumpkin
        reagents:
        - ReagentId: PumpkinFlesh
          Quantity: 4
        - ReagentId: Vitamin
          Quantity: 1
  - type: FoodSequenceElement
    entries:
      Sandwich: CP14PumpkinSandwich

- type: entity
  id: CP14FoodPotato
  parent: FoodInjectableBase
  categories: [ ForkFiltered ]
  name: potato
  description: Cute potato
  components:
  - type: Item
    size: Tiny
  - type: FlavorProfile
    flavors:
      - potatoes
  - type: Sprite
    sprite: _CP14/Objects/Flora/Farm/potato.rsi
    layers:
      - state: base1
        map: [ "random" ]
  - type: RandomSprite
    available:
      - random:
          base1: ""
          base2: ""
          base3: ""
          base4: ""
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 11
        reagents:
        - ReagentId: Nutriment
          Quantity: 7
        - ReagentId: Vitamin
          Quantity: 2
  - type: CP14Seed
    plantProto: CP14PlantPotato #TODO sliceable potato
  - type: Tag
    tags:
    - CP14FarmFood

- type: entity
  id: CP14FoodCucumber
  parent: FoodInjectableBase
  categories: [ ForkFiltered ]
  name: cucumber
  description: An oblong green vegetable. Refreshing!
  components:
  - type: Item
    size: Tiny
  - type: FlavorProfile
    flavors:
      - CP14Water
      - CP14cucumber
  - type: Sprite
    sprite: _CP14/Objects/Flora/Farm/cucumber.rsi
    layers:
      - state: base1
        map: [ "random" ]
  - type: RandomSprite
    available:
      - random:
          base1: ""
          base2: ""
          base3: ""
          base4: ""
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 11
        reagents:
        - ReagentId: Nutriment
          Quantity: 4
        - ReagentId: Vitamin
          Quantity: 2
        - ReagentId: Water
          Quantity: 3
  - type: Tag
    tags:
    - CP14FarmFood
  - type: FoodSequenceElement
    entries:
      Sandwich: CP14CucumberSandwich

- type: entity
  id: CP14FoodTomatoes
  parent: [FoodInjectableBase, ItemHeftyBase]
  categories: [ ForkFiltered ]
  name: tomatoes
  description: A red, juicy tomato. You just want to throw it in someone's face!
  components:
  - type: Item
    size: Tiny
  - type: FlavorProfile
    flavors:
      - tomato
  - type: Sprite
    sprite: _CP14/Objects/Flora/Farm/tomatoes.rsi
    layers:
      - state: base1
        map: [ "random" ]
  - type: RandomSprite
    available:
      - random:
          base1: ""
          base2: ""
          base3: ""
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 12
        reagents:
        - ReagentId: Nutriment
          Quantity: 3
        - ReagentId: Vitamin
          Quantity: 3
        - ReagentId: JuiceTomato
          Quantity: 6
  - type: SliceableFood
    count: 3
    sliceTime: 1
    slice: CP14FoodTomatoesSlice
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 1
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          collection: desecration
      - !type:SpillBehavior
        solution: food
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: Extractable
    grindableSolutionName: food
    juiceSolution:
      reagents:
      - ReagentId: JuiceTomato
        Quantity: 10
  - type: Damageable
    damageContainer: Biological
  - type: DamageOnHighSpeedImpact
    minimumSpeed: 0.1
    damage:
      types:
        Blunt: 1
  - type: Tag
    tags:
    - CP14FarmFood

- type: entity
  id: CP14FoodTomatoesSlice
  parent: FoodInjectableBase
  categories: [ ForkFiltered ]
  name: tomato slice
  description: Thin red tomato slice. It's no longer as nice to throw at people as whole tomatoes.
  components:
  - type: Item
    size: Tiny
  - type: FlavorProfile
    flavors:
      - tomato
  - type: Sprite
    sprite: _CP14/Objects/Flora/Farm/tomatoes.rsi
    layers:
      - state: slice1
        map: [ "random" ]
  - type: RandomSprite
    available:
      - random:
          slice1: ""
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 3 # 1/3 pumpkin
        reagents:
        - ReagentId: Nutriment
          Quantity: 1
        - ReagentId: Vitamin
          Quantity: 1
  - type: FoodSequenceElement
    entries:
      Sandwich: CP14TomatoesSandwich

- type: entity
  id: CP14FoodApple
  parent: FoodInjectableBase
  categories: [ ForkFiltered ]
  name: apple
  description: A fruit for lovers of a quick snack.
  components:
  - type: Item
    size: Tiny
  - type: FlavorProfile
    flavors:
      - apple
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 15
        reagents:
        - ReagentId: Nutriment
          Quantity: 10
        - ReagentId: Vitamin
          Quantity: 4
  - type: Sprite
    sprite: _CP14/Objects/Flora/Farm/apple.rsi
    layers:
      - state: base1
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: JuiceApple
        Quantity: 12
  - type: SliceableFood
    count: 4
    sliceTime: 1.5
    slice: CP14FoodAppleSlice
  - type: Tag
    tags:
    - CP14FarmFood

- type: entity
  id: CP14FoodAppleSlice
  parent: FoodInjectableBase
  categories: [ ForkFiltered ]
  name: apple slice
  description: Small slices to eat at one time.
  components:
  - type: Item
    size: Tiny
  - type: FlavorProfile
    flavors:
      - apple
  - type: Sprite
    sprite: _CP14/Objects/Flora/Farm/apple.rsi
    layers:
      - state: slice1
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 4
        reagents:
        - ReagentId: Nutriment
          Quantity: 2.5
        - ReagentId: Vitamin
          Quantity: 1
  - type: FoodSequenceElement
    entries:
      Sandwich: CP14AppleSandwich

- type: entity
  id: CP14FoodPepper
  parent: FoodInjectableBase
  categories: [ ForkFiltered ]
  name: pepper
  description: Red and sweetish.
  components:
  - type: Item
    size: Tiny
  - type: FlavorProfile
    flavors:
      - peppery
  - type: Sprite
    sprite: _CP14/Objects/Flora/Farm/pepper.rsi
    layers:
      - state: base1
        map: [ "random" ]
  - type: RandomSprite
    available:
      - random:
          base1: ""
          base2: ""
          base3: ""
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 15
        reagents:
        - ReagentId: Nutriment
          Quantity: 8
        - ReagentId: Vitamin
          Quantity: 6
  - type: Tag
    tags:
    - CP14FarmFood

- type: entity
  id: CP14FoodOnion
  parent: FoodInjectableBase
  categories: [ ForkFiltered ]
  name: onion
  description: If you eat too much, you can cry tears of joy.
  components:
  - type: Item
    size: Tiny
  - type: FlavorProfile
    flavors:
      - onion
  - type: Sprite
    sprite: _CP14/Objects/Flora/Farm/onion.rsi
    layers:
      - state: base1
        map: [ "random" ]
  - type: RandomSprite
    available:
      - random:
          base1: ""
          base2: ""
          base3: ""
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 17
        reagents:
        - ReagentId: Nutriment
          Quantity: 9
        - ReagentId: Vitamin
          Quantity: 4
        - ReagentId: Allicin
          Quantity: 3
  - type: CP14Seed
    plantProto: CP14PlantOnion
  - type: Tag
    tags:
    - CP14FarmFood
