- type: entity
  id: CP14FoodCabbage
  parent: FoodInjectableBase
  name: cabbage
  description: Green edible ball.
  components:
  - type: Item
    size: Normal
  - type: FlavorProfile
    flavors:
      - cabbage
  - type: Sprite
    sprite: _CP14/Objects/Flora/Farm/cabbage.rsi
    layers:
      - state: base1
        map: [ "random" ]
  - type: RandomSprite
    available:
      - random:
          base1: ""
          base2: ""
          base3: ""
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 12
        reagents:
        - ReagentId: Nutriment
          Quantity: 10
        - ReagentId: Vitamin
          Quantity: 1
  - type: SliceableFood
    count: 4
    sliceTime: 1.5
    slice: CP14FoodCabbageSlice

- type: entity
  id: CP14FoodCabbageSlice
  parent: FoodInjectableBase
  name: cabbage leaf
  description: Time to make green salads
  components:
  - type: Item
    size: Tiny
  - type: FlavorProfile
    flavors:
      - cabbage
  - type: Sprite
    sprite: _CP14/Objects/Flora/Farm/cabbage.rsi
    layers:
      - state: slice1
        map: [ "random" ]
  - type: RandomSprite
    available:
      - random:
          slice1: ""
          slice2: ""
          slice3: ""
          slice4: ""
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 3 # 1/4 cabbage
        reagents:
        - ReagentId: Nutriment
          Quantity: 2.5
        - ReagentId: Vitamin
          Quantity: 0.25
  - type: FoodSequenceElement
    entries:
      CP14Plate: CP14PlateCabbageSlice

- type: entity
  id: CP14FoodPumpkin
  parent: FoodInjectableBase
  name: pumpkin
  description: Big, cool pumpkin. 
  components:
  - type: Item
    size: Normal
  - type: FlavorProfile
    flavors:
      - pumpkin
  - type: Sprite
    sprite: _CP14/Objects/Flora/Farm/pumpkin.rsi
    layers:
      - state: base1
        map: [ "random" ]
  - type: RandomSprite
    available:
      - random:
          base1: ""
          base2: ""
          base3: ""
          base4: ""
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 30
        reagents:
        - ReagentId: PumpkinFlesh
          Quantity: 20
        - ReagentId: Vitamin
          Quantity: 5
  - type: SliceableFood
    count: 5
    sliceTime: 2
    slice: CP14FoodPumpkinSlice

- type: entity
  id: CP14FoodPumpkinSlice
  parent: FoodInjectableBase
  name: pumpkin slice
  description: Pumpkin! # TODO
  components: 
  - type: Item
    size: Tiny
  - type: FlavorProfile
    flavors:
      - pumpkin
  - type: Sprite
    sprite: _CP14/Objects/Flora/Farm/pumpkin.rsi
    layers:
      - state: slice1
        map: [ "random" ]
  - type: RandomSprite
    available:
      - random:
          slice1: ""
          slice2: ""
          slice3: ""
          slice4: ""
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 6 # 1/5 pumpkin
        reagents:
        - ReagentId: Nutriment
          Quantity: 4
        - ReagentId: Vitamin
          Quantity: 1
  - type: FoodSequenceElement
    entries:
      CP14Plate: CP14PlatePumpkinSlice

- type: entity
  id: CP14FoodPotato
  parent: FoodInjectableBase
  name: potato
  description: Cute potato
  components:
  - type: Item
    size: Tiny
  - type: FlavorProfile
    flavors:
      - potatoes
  - type: Sprite
    sprite: _CP14/Objects/Flora/Farm/potato.rsi
    layers:
      - state: base1
        map: [ "random" ]
  - type: RandomSprite
    available:
      - random:
          base1: ""
          base2: ""
          base3: ""
          base4: ""
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 11
        reagents:
        - ReagentId: Nutriment
          Quantity: 7
        - ReagentId: Vitamin
          Quantity: 2
  - type: CP14Seed
    plantProto: CP14PlantPotato #TODO sliceable potato

- type: entity
  id: CP14FoodCucumber
  parent: FoodInjectableBase
  name: cucumber
  description: An oblong green vegetable. Refreshing!
  components:
  - type: Item
    size: Tiny
  - type: FlavorProfile
    flavors:
      - CP14Water #TODO
  - type: Sprite
    sprite: _CP14/Objects/Flora/Farm/cucumber.rsi
    layers:
      - state: base1
        map: [ "random" ]
  - type: RandomSprite
    available:
      - random:
          base1: ""
          base2: ""
          base3: ""
          base4: ""
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 11
        reagents:
        - ReagentId: Nutriment
          Quantity: 4
        - ReagentId: Vitamin
          Quantity: 2
        - ReagentId: Water
          Quantity: 3
  - type: FoodSequenceElement
    entries:
      CP14Plate: CP14PlateCucumber