- type: entity
  id: CP14FoodCabbage
  parent: FoodInjectableBase
  name: cabbage
  description: Green edible ball.
  components:
  - type: Item
    size: Normal
  - type: FlavorProfile
    flavors:
      - cabbage
  - type: Sprite
    sprite: _CP14/Objects/Specific/Farming/Produce/cabbage.rsi
    layers:
      - state: base1
        map: [ "random" ]
  - type: RandomSprite
    available:
      - random:
          base1: ""
          base2: ""
          base3: ""
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 14
        reagents:
        - ReagentId: Nutriment
          Quantity: 10
        - ReagentId: Vitamin
          Quantity: 4
  - type: SliceableFood
    count: 4
    slice: CP14FoodCabbageSlice

- type: entity
  id: CP14FoodCabbageSlice
  parent: CP14FoodCabbage
  name: cabbage leaf
  description: Time to make green salads
  components:
  - type: Item
    size: Tiny
  - type: Sprite
    layers:
      - state: slice1
        map: [ "random" ]
  - type: RandomSprite
    available:
      - random:
          slice1: ""
          slice2: ""
          slice3: ""
          slice4: ""
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 3.5 # 1/4 cabbage
        reagents:
        - ReagentId: Nutriment
          Quantity: 2.5
        - ReagentId: Vitamin
          Quantity: 1