- type: entity
  abstract: true
  parent: Clothing
  id: CP14ClothingHeadBase
  categories: [ ForkFiltered ]
  components:
  - type: Clothing
    equipDelay: 0.3
    unequipDelay: 0.3
    slots:
    - HEAD
    breakOnMove: false
  - type: Sprite
    state: icon
  - type: Item
    size: Normal
    storedRotation: -90
