- type: entity
  id: CP14BaseExpedition
  categories: [ HideSpawnMenu ]
  parent:
  - BaseStation
  - BaseStationAllEventsEligible
  - BaseStationJobsSpawning
  - BaseStationAlertLevels #Checks fail without it
  - CP14BaseTrading
  - CP14BaseCommonObjectives

- type: entity
  id: CP14BaseTrading
  abstract: true
  components:
    - type: CP14StationTravelingStoreShipTarget

- type: entity
  id: CP14BaseCommonObjectives
  abstract: true
  components:
    - type: CP14StationCommonObjectives