- type: entity
  id: CP14BaseExpedition
  categories: [ HideSpawnMenu ]
  parent:
  - BaseStation
  - BaseStationAllEventsEligible
  - BaseStationJobsSpawning
  - BaseStationAlertLevels #Checks fail without it
  - BaseStationRecords # Required for lobby manifest + cryo leave
  - CP14BaseStationTrading
  - CP14BaseStationCommonObjectives
  - CP14BaseStationSalary

- type: entity
  id: CP14BaseStationTrading
  abstract: true
  components:
    - type: CP14StationTravelingStoreShipTarget

- type: entity
  id: CP14BaseStationCommonObjectives
  abstract: true
  components:
    - type: CP14StationCommonObjectives

- type: entity
  id: CP14BaseStationSalary
  abstract: true
  components:
    - type: CP14StationSalary
      #frequency: every 20 minutes
      salary:
        CP14Guard: 550