- type: entity
  id: CP14BaseExpedition
  categories: [ HideSpawnMenu ]
  parent:
  - BaseStation
  - BaseStationAllEventsEligible
  - BaseStationJobsSpawning
  - CP14BaseTownAlerts
  - BaseStationRecords # Required for lobby manifest + cryo leave
  - CP14BaseStationCommonObjectives
  - CP14BaseStationDemiplaneMap

- type: entity
  id: CP14BaseStationCommonObjectives
  abstract: true
  components:
    - type: CP14StationCommonObjectives

- type: entity
  id: CP14BaseTownAlerts
  abstract: true
  components:
    - type: AlertLevel
      alertLevelPrototype: CP14TownAlerts

- type: entity
  id: CP14BaseStationDemiplaneMap
  abstract: true
  components:
    - type: CP14StationDemiplaneMap
